chaosblade-io/chaosblade-exec-os

exec/bin/burncpu/burncpu.go
exec/bin/burncpu/burncpu_test.go
exec/bin/burncpu/forlinux/burncpu.go
exec/bin/burncpu/forlinux/burncpu_test.go

fix cpu bind not correct.
Fix #1 
when use taskset for binding cpu :
man taskset:
-a, --all-tasks
Set or retrieve the CPU affinity of all the tasks (threads) for a given PID.
add -a to taskset command.
```
response := channel.Run(ctx, "taskset", fmt.Sprintf("-a -cp %s %d", core, pid))
```
when use cgorup for binding cpu
update cpuset.cpus to bind:
```
cgctrl.Update(&specs.LinuxResources{CPU: &specs.LinuxCPU{Cpus: cpuList}});
```
taskset:
pidstat -p $pid 1 
cgroup:
```
cat  /sys/fs/cgroup/cpuset/chaosblade/cpuset.cpus
```

fix cpu-binding both cpuset & cgroup. relate to #1

---

exec/bin/burnio/burnio.go
exec/bin/filldisk/filldisk.go

See chaosblade-io/chaosblade#238 for details.
Replace `content.Backgroud()` to `content.TODO()` because if the context is content.Background(), it will be replaced with `context.WithTimeout()` with 60s timeout in chaosblade-io/chaosblade-spec-go project.

bugfix: fix disk experiments cannot be continuously run

---

exec/disk_burn.go
exec/disk_fill.go
exec/network.go
exec/network_delay.go
exec/network_dns.go
exec/process_stop.go
exec/script.go

See chaosblade-io/chaosblade#239 for the deails.
Add `requiredWhenDestroyed` filed in flag which is necessary when destroying.
Create network experiments to verify with destroy uid and destroy <TARGET> <ACTION> <OPTIONS> commands, for examples:
```
blade create network delay --time 3000 --interface eth0 --local-port 6379
blade destroy network delay --interface eth0
blade create network loss --percent 50 --interface eth0 --local-port 6379
blade destroy e3a76030daeaebc3
```

feature: enhance destroy command

---

exec/bin/burncpu/burncpu.go
exec/bin/burnio/burnio.go
exec/bin/burnmem/burnmem.go
exec/bin/changedns/changedns.go
exec/bin/common.go
exec/bin/delaylossnetwork/delaylossnetwork.go
exec/bin/dropnetwork/dropnetwork.go
exec/bin/filldisk/filldisk.go
exec/bin/filldisk/filldisk_test.go
exec/bin/killprocess/killprocess.go
exec/bin/stopprocess/stopprocess.go
exec/cpu.go
exec/disk_burn.go
exec/disk_fill.go
exec/mem.go
exec/network_dns.go
exec/network_drop.go
exec/network_loss.go
exec/process_kill.go
exec/process_stop.go

It is easier to specify the disk size 
chaosblade-io/chaosblade#241
1. Add percent flag in disk fill experiment.
2. If both size and percent flags are present, the percent flag is preferred.
3. Calculate disk usage and compare to the percent value. If the current disk usage greater than the percent, the blade returns error. Otherwise, subtractusage from the value of percent and multiply the total disk size to get the desired value.
`blade c disk fill --percent 60 --path /home/admin`

Support percentage of disk size in disk fill experiment

---

exec/process_kill.go
exec/process_stop.go
go.mod
go.sum

See chaosblade-io/chaosblade#255 for details.
Add double quotes for process names.

bugfix: fix process filter under process name contains blank condition

---

exec/bin/burnmem/burnmem.go
exec/bin/burnmem/burnmem_test.go
exec/mem.go

support cache and ram mode for mem load experiment
Fixes:  https://github.com/chaosblade-io/chaosblade/issues/278
1. add --rate and --mode flags for mem load experiment
2. use buff chan to fill the mem with golang

feature: add rate and mode flags for mem load experiment

---

exec/bin/burnmem/burnmem.go

1. change buff chan size to int64
2. make ram mode still works if `--rate` flags is not defined
Fixs: https://github.com/chaosblade-io/chaosblade/issues/285

bugxif: fix buff chan size to support large memory machine

---

Makefile
exec/bin/tcnetwork/tcnetwork.go
exec/bin/tcnetwork/tcnetwork_test.go
exec/network.go
exec/network_duplicate.go
exec/network_loss.go

See chaosblade-io/chaosblade#292
1. Add network duplication action.
2. Modify the original `dlnetwork` directory and file to `tcnetwork` to support more network chaos experiments, such as packet duplication, package re-ordering and packet corruption.
Execute the following command to cause 50 percent packets duplication when request the 80 remote port :
```
blade c network duplicate  --percent 50 --interface eth0 --remote-port 80 --debug
```
Use `tcpdump` command to capture communication data on remote port 80 to record test-chaosblade-duplicate-80.pcap file:
```
tcpdump -vv -tttt -S -i eth0 -s 0 -w test-chaosblade-duplicate-80.pcap dst host 180.101.49.11 and port 80
```
Request the remote http service:
```
curl 180.101.49.11
```
Download the test-chaosblade-duplicate-80.pcap file and …

feature: support network packets duplication

---

exec/bin/tcnetwork/tcnetwork.go
exec/network.go
exec/network_corrupt.go
exec/network_reorder.go

See chaosblade-io/chaosblade#293
1. Add `reorder` action contains `percent`, `correlation`, `gap` and `time` flags.
2. Add `corrupt` action contains `percent` flag.
Execute the following command to verify reorder:
```
blade c network reorder --percent 75 --correlation 50 --destination-ip 100.xxx.xxx.xxx  --interface eth0 --time 1200
```
Use `ping 100.xxx.xxx.xxx -A` to verify:
Execute the following command to verify corrupt:
```
blade c network corrupt --percent 75 --interface eth0 --destination-ip 100.xx.xx.xx
```
Use `ping 100.xxx.xxx.xxx -A` to verify:

feature: add network packet re-ordering and corruption

---

exec/bin/burnio/burnio.go
exec/bin/burnmem/burnmem.go
exec/bin/burnmem/burnmem_test.go
exec/disk_fill.go

See #18 
1. Cache objects with map and slice.
2. If the memory to be occupied is less than the value of `rate`, apply for 10% of the memory with expect occupation each time. Default rate is 100M/S. You can use `--rate` to specify the value.
3. If the size of the slice during expansion(cap * 1.25) is greater than the size of the memory to be occupied, a new slice is created and cached in the map.
```
blade create mem load --mode ram --mem-percent 90 --rate 10
```

bugfix: fix simulation of memory usage experiment using ram mode

---

exec/disk_burn.go
exec/disk_fill.go
exec/process_stop.go

See chaosblade-io/chaosblade#324 for the details.
Delete unnecessary `requiredWhenDestroyed` flag.
```
blade c network delay --time 3000 --interface eth0 --remote-port 80
blade d network delay --time 3000 --interface eth0 --remote-port 80
```

feature: remove unnecessary flag when destroying

---

exec/bin/filldisk/filldisk.go
exec/bin/filldisk/filldisk_test.go
exec/disk_fill.go
go.mod
go.sum

chaosblade-io/chaosblade#325
Add `retain-handle` flag to hold the file handle.
```
blade c disk fill --retain-handle --percent 50
```
Use lsof command to lookup file handle:
```
lsof | grep chaos_filldisk.log.dat
chaos_fil 26833          root    3r      REG              253,1 6320816128         18 /chaos_filldisk.log.dat
chaos_fil 26833 26834    root    3r      REG              253,1 6320816128         18 /chaos_filldisk.log.dat
chaos_fil 26833 26835    root    3r      REG              253,1 6320816128         18 /chaos_filldisk.log.dat
chaos_fil 26833 26836    root    3r      REG              253,1 6320816128         18 /chaos_filldisk.log.dat
chaos_fil 26833 26838    root    3r      REG              253,1 6320816128         18 …
```

feature: add retain-handle flag in disk fill experiment

---

.editorconfig
exec/bin/burncpu/burncpu.go

add caught interrupt supprot for graceful exiting
The `kill -9 <pid>`  command is kill process by OS that will be caught resources (eg memory, disk read handler..) not recycle not immediately. So `kill -HUP` is good choice to exiting or stop process more graceful. see more https://en.wikipedia.org/wiki/Kill_(command).
btw: I consider directory `forlinux` maybe duplicate?

add caught interrupt supprot for graceful exiting

---

exec/bin/burnmem/burnmem.go
exec/mem.go

`./blade c mem load --mode ram --mem-percent 50 `
Most of the monitoring percentage calculations do not include buffer/cache, resulting in memory experiments not meeting the monitored warning indicators
`./blade c mem load --mode ram --mem-percent 50 --exclude-buffer-cache`

feature:add --exclude-buffer-cache flag for mem experiment ram model

---

exec/bin/burncpu/burncpu.go
exec/cpu.go

make CPU slowly climb to some level, to simulate slow resource competition which system faults cannot be quickly noticed by monitoring system
add a ticker to control cpuPercent
```bash 
./chaos_burncpu  -nohup -cpu-percent 80 -climb-time 120
```

add cpu climb time feature (conflict fix)

---

exec/bin/file/appendfile/appendfile.go
exec/file_append.go

append file content support base64 encoding
`blade create file append --filepath=/root/chaosblade/mock.log --content="XCRcJGFiY1wkXCQgIEB7REFURTorJVktJW0tJWQgJUg6JU06JVN9IEVSUk9SIGNiYSBAe1JBTkRPTToxMDAtMjAwfSBhYmMgIG1vY2sgZXhjZXB0aW9u" --enable-base64=true`

feature:append file content support base64 encoding

---

exec/bin/burnio/burnio.go

Bugfix.
`Signal killed` returned when the disk burn scenario is destroying.
Exclude keyword of destroying process.
Package and test it.

bugfix: fix stopping disk io burning failed

---

exec/bin/killprocess/killProcess_test.go
exec/bin/killprocess/killprocess.go
exec/bin/stopprocess/stopprocess.go
exec/process.go
exec/process_kill.go
exec/process_stop.go

Sometimes it is expected that the process does not exist.
Add `--ignore-not-found` flag in process scenarios.
```
blade c process kill --process tomcat --ignore-not-found
```

feature: add ignore-not-found flag in process experiments

---

exec/bin/burnmem/burnmem.go

https://github.com/chaosblade-io/chaosblade/issues/425
````
blade create docker mem load --mode ram --mem-percent 50  --container-id 3d263897bb387b18670d53efc6cff0383c25887bb03deb47cf91125bc56e4fe5 --blade-tar-file ../chaosblade-0.7.0.tar.gz
````
````
docker stats 3d263897bb387b18670d53efc6cff0383c25887bb03deb47cf91125bc56e4fe5
````

feature:exclude cache in cantainer

---

exec/bin/tcnetwork/tcnetwork.go

#https://github.com/chaosblade-io/chaosblade/issues/402
exec comannd
````
./blade create network loss --percent 100 --interface eth0 --exclude-port 22,9526,80 --debug
````
Nothing takes effect except port 22

fixbug: Multiple exclude-port is invalid

---

exec/bin/burncpu/burncpu.go

Under some systems, processes cannot exit using kill -HUP
#27 #66 
In the destroy phase, kill -9 is used
````
blade create cpu load --cpu-percent 60
````
After a while
````
blade destroy cpu load --debug
````

fixbug: Under some systems, processes cannot exit using kill -HUP

---

exec/bin/tcnetwork/tcnetwork.go

chaosblade-io/chaosblade#453
I expect that when the exclude-port and exclude-ip flags are used at the same time, the exclude-port and exclude-ip flags take effect separately instead of being combined together like ip:port.
For example, --exclude-ip 1.1.1.1 --exclude-port 80 flags exclude 1.1.1.1 and 80 instead of 1.1.1.1:80
1. When `local-port` or `remote-port` is used with `destination-ip`, the `destination-ip:local-port` or `destination-ip:remote-port` takes effect. For example:
```
{"code":200,"success":true,"result":"d605e9999397ac82"}
PING 61.155.221.xxx (61.155.221.xxx) 56(84) bytes of data.
64 bytes from 61.155.221.xxx: icmp_seq=1 ttl=53 time=14.6 ms
--- 61.155.221.xxx ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, …
```

bugfix: fix using both exclude-port and exclude-ip flags

---

exec/cpu.go

Update a description in the documentation.
Yes
Fix typo
No need.

typofix: change cpu's kernel to core.

---

exec/bin/tcnetwork/tcnetwork.go

[network delay] It doesn't work with the flag 'exclude-port'.
NO

bugfix: It doesn't work with the flag 'exclude-port'

---

Makefile
build/spec.go
exec/bin/stopsystemd/stopsystemd.go
exec/category/category.go
exec/model/model.go
exec/systemd.go
exec/systemd_stop.go

Stop system service for a while to simulate the scene of system down
https://github.com/chaosblade-io/chaosblade/issues/518
blade create systemd stop --service SERVICE_NAME

Add systemd stop feature

---

exec/bin/burnio/burnio.go

RCA : different version of dd command between different Linux release version.
link: https://github.com/chaosblade-io/chaosblade-exec-os/issues/93
This modification mainly adds some conditions to determine the appropriate dd command parameters for different Linux versions (right now is Alpine Linux)
Fixes #93 
This modification mainly adds some conditions to determine the appropriate dd command parameters for different Linux versions (right now is Alpine Linux)
Tested in local UAT kubernetes Env.
At the time, the main branch was not be able to be compiled, the error is from system_stop.go, please take a look.
My real test is base on v1.2.0.

fix: Disk burn experiment failed in Kubernetes

---

exec/network_delay.go

the default offset was always set to 10ms, it's not possible if we want a constant delay time.
and it is not documentated.
set default value to 0

network delay: set default offset value to 0.

---

exec/bin/tcnetwork/tcnetwork.go

Signed-off-by: jfl929930 <jfl01231489@alibaba-inc.com>
When the non root account of Linux performs fault injection, failure will be displayed when the non root account is destroyed. In fact, it is a failure. This is a problem.
Fixes #597
Judge whether the TC command is executed successfully. If it is successful, it will be destroyed. If it is unsuccessful, an error will be returned and the fault status will not be modified

The problem of wrong return value of destroy under non root Linux

---

exec/bin/tcnetwork/tcnetwork.go

Signed-off-by: xcaspar <changjun.xcj@alibaba-inc.com>
Solve the problem of using the `--force` flag to return a `RTNETLINK answers: Invalid argument\\nWe have an error talking to the kernel` error.
Use uid equal to 0 to determine the execution authority.
Package and test it.
```
{"code":200,"success":true,"result":"b09acbf1e9c5617e"}
{"code":200,"success":true,"result":"0bfdf627300c4c35"}
```

Fix the error when destroying the network experiment

---

Makefile
exec/bin/burnmem/burnmem.go

Signed-off-by: xcaspar <changjun.xcj@alibaba-inc.com>
Modify the file written to the oom score from `/proc/%s/oom_score_adj` to `/proc/%s/oom_adj`.
Package and test it.
```
blade c mem load --avoid-being-killed --mode ram
```
The`--avoid-being-killed` flag must be added to prevent the process from being killed.

Fix memory overflow experimental scene problem

---

exec/bin/file/appendfile/appendfile.go
main.go

Signed-off-by: xcaspar <changjun.xcj@alibaba-inc.com>
chaosblade-io/chaosblade#636
Solve the problem of equal sign under base64 encoding.
Package and test it.
```
[root@zk003 chaosblade-1.4.0]# ./blade create file append --debug 'true' --filepath '/root/common-alarm.log' --count '2' --enable-base64 'true' --interval '1' --content 'eyJrZXl3b3JkIjoiU2FlSm9iRXJyb3IiLCJtZXNzYWdlIjoiY2hhb3MtLUt1YmVybmV0ZXNBY3JUb2tlblVwZGF0ZUpvYiNoYW5kbGVTeW5jQnlLOHNOYW1lc3BhY2UgZXhlY3V0ZSBlcnJvciwgcGxlYXNlIGNoZWNrIHlvdSBqb2IhIGVycm9yIG1lc3NhZ2UgaXMgSW52b2NhdGlvbiBmYWlsZWQuIiwidGltZSI6MTYzOTY3MDU1MTY5OX0='
{"code":200,"success":true,"result":"a31d75e1dd39a999"}
```
```
#cat /root/common-alarm.log
{"keyword":"SaeJobError","message":"chaos--KubernetesAcrTokenUpdateJob#handleSyncByK8sNamespace execute error, …
```

Fix the execution failure of file content appending scene

---

exec/cpu/cpu.go
exec/cpu/cpu_darwin.go
exec/cpu/cpu_linux.go

The cpu.Percent returns an array when percpu is true and a single value when percpu is false.
Its semantics should be per CPU instead of previous CPU

fix: fix cpu variable name precpu to perCpu

---

exec/exec.go

Signed-off-by: Super-long <0x4f4f4f4f@gmail.com>
Take the generated expblade create cpu fullload --cpu-count 1 as an example.
When we execute the blend destroy uid, chaosblade is actually chaos_os destroy cpu fullload --cpu-count=1 --uid=e39ebc941a451b15 sent to exec-os first
The behavior at this point is that chaosblade destroys all chaos-related experiences. The root of the problem comes from Destroy, which lacks a judgment on the suid when looking for the pid to be deleted.
So even if we specify the uid in destroy, all chaos-related experiments will actually be deleted.
Translated with www.DeepL.com/Translator (free version)
https://github.com/chaosblade-io/chaosblade/issues/46
Add suid support for Destroy function.
One of the judgments in the added code is ”spec.UnknownUid“, which …

fix: Fix deleting multiple experiments when specifying uid.

---

exec/exec.go
main.go

Signed-off-by: Icesource <gonghuajian.ghj@alibaba-inc.com>
For https://github.com/chaosblade-io/chaosblade/issues/46
when exp is destroy mode, suid is always generated randomly. But suid is not required in destroy mode. And it also causes the wrong suid to be specified when destroying the Cpu scene.

fix: fix cpu exp destroy mode when suid is empty

---

exec/mem/mem.go
exec/network/tc/network_tc.go

bugs:
- network port parse
- mem exp avoid-being-killed flag invlid

Fixed issues left over from version 1.6.0

---

exec/network/tc/network_tc.go

Signed-off-by: Icesource <gonghuajian.ghj@alibaba-inc.com>
for #119 , In network experiments, exclude-port support ipv6
Fix #119

fix: exclude port not work in ipv6

---

exec/mem/mem_linux.go

Signed-off-by: tiny-x <xf.yefei@gmail.com>
Fix failed to get free memory correctly in container.

fix: pod mem exp.

---

build/spec.go
exec/model/model_linux.go
exec/time/time.go
exec/time/time_travel.go

Signed-off-by: Icesource <gonghuajian.ghj@alibaba-inc.com>
新增Time Travel故障类型，可修改系统时间
时钟偏移可以让节点看到的系统时间出现偏移，验证分布式系统下依赖于时间同步的逻辑是否会由于单点时间异常而出现异常
例如验证Mysql主从复制下，会不会由于从节点时间错误导致数据不一致
或者分布式数据库的时钟一致性能否在节点系统时间异常的情况下正常工作
执行date命令修改系统时间，销毁则通过hwclock将硬件时钟同步到系统时间
TODO：date指令仅能粗粒度修改系统时间，之后需要探索实现容器进程维度修改时间的方法
time travel 至 10m30s之后
```
date
2022年 08月 25日 星期四 15:36:06 CST
./target/chaosblade-1.6.1/bin/chaos_os create time travel --offset 10m30s
{"code":200,"success":true,"result":"2022年 08月 25日 星期四 15:47:08 CST\n"}
// 系统时间修改为了10分30秒之后，执行chaos_os destroy time travel --offset 10m30s可恢复
./target/chaosblade-1.6.1/bin/chaos_os create time travel --offset -4m27s
{"code":200,"success":true,"result":"2022年 08月 25日 星期四 15:34:22 CST\n"}
// 系统时间修改为了4分27秒之前
```

feat: add time travel experiment

---

exec/process/process.go
exec/process/process_kill.go
exec/process/process_stop.go

Signed-off-by: EdisonX-sudo <387617982@qq.com>
feature: made process kill and stop support --pid flag
in some occasion, we still need to kill or stop process by declaring a specified pid explicitly
create process kill --signal 9 --pid 1227
create process stop --pid 1227

feature: made process kill and stop support --pid flag

---

exec/cpu/cpu.go

Fix variable name.
Run make build_linux will failed by error `exec/cpu/cpu.go:287:51: undefined: precpu`
In `exec/cpu/cpu.go` variable `percpu` name not consistent, both `percpu` and `precpu`

Fix variable name error, from precpu to percpu.

---

exec/systemd/systemd_stop.go

Signed-off-by: Yuaninga <1846225041@qq.com>
This PR will fix the bug: failed to create the systemd experiment.
[bug report： the systemd stop experiment cannot be created #815](https://github.com/chaosblade-io/chaosblade/issues/815)
The`StopSystemdBin` will be no longer used in the code, but `systemctl stop service` that  realized  the `StopSystemdBin`  will be used directly.
1.Build a new chaos_os  in  the chaosblade-exec-os
`cd chaosblade-exec-os`
`make build_linux` (on the Mac operating system)
`cd  target/chaosblade-1.7.0/bin`
2.Move the new chaos_os to the chaosblade-1.7.0 from the chaosblade-exec-os
`scp chaos_os root@x.x.x.x:/root/chaosblade-1.7.0`
3.Replace the old chaos_os
`ssh root@x.x.x.x`
`cd chaosblade-1.7.0/bin`
`mv chaos_os chaos_os_old`
`cd ..`
`mv chaos_os bin/chaos_os` …

fix: failed to create the systemd experiment

---

exec/network/tc/network_tc.go

Signed-off-by: Xianglin Gao <xianglingao@tencent.com>
When I run network loss experiment with exclude port. I find following log:
```
time="2023-02-01 11:15:24.317567738 CST" level=debug msg="Command Result, output: /bin/sh: line 4: ,: command not found\n/bin/sh: line 6: ,: command not found\n/bin/sh: line 8: ,: command not found\n/bin/sh: line 10: ,: command not found\n/bin/sh: line 12: ,: command not found\n/bin/sh: line 14: ,: command not found\n/bin/sh: line 16: ,: command not found\n, err: <nil>"
```
When I look at the code, I found out an extra `,` in https://github.com/chaosblade-io/chaosblade-exec-os/blob/e2893ec5c0b2e888ad80a71528bee3978c9a8d99/exec/network/tc/network_tc.go#L197  After I remove the `,`, it worked fine.
Remove the `,`
Run network loss experiment with exclude …

fix error when use exclude port in tc

---

exec/systemd/systemd_stop.go

Remove the unused import pkg path in `exec/systemd/systemd_stop.go`

fix: Remove unused import pkg path

---

exec/network/network_dnsdown.go
exec/network/network_linux.go

Add the DNS down failure feature that can make domain name resolution impossible within the host. This fault supports adding domain names that allows normal access using the parameter `allow_domain`.
iptables
- make dns down and no domain will be resolved properly.
`blade create network dns_down`
- make dns down while aliyun.com and taobao.com will be be resolved properly.
`blade create network dns_down --allow_domain=aliyun.com,taobao.com`

feature: Add dns down

---

exec/file/file_append.go
exec/systemd/systemd_stop.go

This PR will fix the bug: the file append experiment is unreasonable.
[bug report： the file append experiment is unreasonable #824](https://github.com/chaosblade-io/chaosblade/issues/824)
This PR contains another pr that has not been merged:
[fix: failed to create the systemd experiment #147](https://github.com/chaosblade-io/chaosblade-exec-os/pull/147)
Without interval parameter, it will not be executed regularly.
1.Build a new chaos_os in the chaosblade-exec-os
`cd chaosblade-exec-os`
`make build_linux (on the Mac operating system)`
`cd  target/chaosblade-1.7.0/bin`
2.Move the new chaos_os to the chaosblade-1.7.0 from the chaosblade-exec-os
`scp chaos_os root@x.x.x.x:/root/chaosblade-1.7.0`
3.Replace the old chaos_os
`ssh root@x.x.x.x`
`cd chaosblade-1.7.0/bin`
`mv chaos_os …

fix：the file append experiment is unreasonable

---

exec/process/process.go
exec/process/process_load.go

feature: add process load
create process load by create ping process

feature add process load

---

exec/time/time_travel.go

Fix cmd time category

---

exec/file/file_add.go

fixes:https://github.com/chaosblade-io/chaosblade/issues/796

file add echo add -e param

---

exec/exec.go

Fix https://github.com/chaosblade-io/chaosblade/issues/1138
The ping process has been properly cleared during the destory process, so there is no need to clear the chaos_os process. Therefore, if the chaos_os process cannot be found during the destory process, a success message is returned.
```
{"code":200,"success":true,"result":"342e0edd01cb14a6"}
{"code":200,"success":true,"result":{"target":"process","action":"load","flags":{"count":"10","debug":"true"},"ActionProcessHang":false}}
root     3613929 3585100  0 20:54 pts/0    00:00:00 grep --color=auto ping
```

Bugfix: Fix destory process load scenario error

---

exec/time/time_travel.go

Enhance https://github.com/chaosblade-io/chaosblade/issues/1139
Removed mandatory dependency on timedatectl.
* Previously, both timedatectl and date were required to be available. Now, only the date command is required, making timedatectl optional.
* Intelligent command detection.
Dynamic detection of the availability of timedatectl.
* Selecting the best time modification strategy based on the available commands.
* Multiple time format support.
* ISO format: 2006-01-02 15:04:05
* Original format: 01/02/2006 15:04:05
* ISO without spaces: 2006-01-02T15:04:05
* Unix format: Jan 2 15:04:05 2006.
Graceful error handling.
* Logs a warning but continues execution when NTP is not supported.
* Provides detailed error information and logging.
Alternative time setting methods.
* Prefers multiple …

Feature: Enhance time travel scene compatibility
