chaosblade-io/chaosblade-exec-os

exec/cpu.go
exec/disk.go
exec/disk_burn.go
exec/mem.go
exec/network.go
exec/network_delay.go
exec/network_dns.go
exec/network_drop.go
exec/network_loss.go
exec/process.go
exec/process_kill.go
exec/process_stop.go
exec/script.go
exec/script_delay.go
exec/script_exit.go

feature: add the required commands check

---

exec/bin/killprocess/killprocess.go
exec/process_kill.go

chaosblade-io/chaosblade#249
Add `count` flag in kill process experiment.
`blade create process kill --count 1 --process tomcat`

feature: support count limit in kill process experiment

---

exec/bin/burnio/burnio.go
exec/bin/burnmem/burnmem.go
exec/bin/filldisk/filldisk.go
exec/disk_fill.go
exec/mem.go

1. add reserve flag for mem load and disk fill experiments
2. get  memory info for cgroup if the process has mem limit
Fixes https://github.com/chaosblade-io/chaosblade/issues/270

feature: add reserve flag for mem load and disk fill experiments

---

exec/bin/filldisk/filldisk.go
exec/bin/filldisk/filldisk_test.go

See chaosblade-io/chaosblade#315
Modify the code to support the update of github.com/chaosblade-io/chaosblade-spec-go/channel 
https://github.com/chaosblade-io/chaosblade-spec-go/commit/956c50c757ebe817ce418af124b21c1236561668

bugfix: filldisk can not be compiled

---

exec/bin/tcnetwork/tcnetwork.go
exec/network.go
exec/network_corrupt.go
exec/network_delay.go
exec/network_duplicate.go
exec/network_loss.go
exec/network_reorder.go

feature: add force flag for network experiments

---

Makefile
exec/bin/occupynetwork/occupynetwork.go
exec/network.go
exec/network_occupy.go

chaosblade-io/chaosblade#345
```
blade c network occupy --port 8182
blade c network occupy --port 8182 --force
```

feature: support port occupation expriment

---

exec/network.go

add exclude-ip

---

exec/network.go

Remove excess exclude-ip.

---

exec/bin/killprocess/killprocess.go
exec/process_kill.go

chaosblade-io/chaosblade#357
Add `signal` flag.
```
blade create process kill --process top
blade create process kill --process top --signal 15
```

feature: add signal flag in killing process experiment

---

exec/bin/killprocess/killprocess.go
exec/process_kill.go

this PR add exclude-process flag in killing process experiment

feature:add exclude-process flag in killing process experiment

---

Makefile
exec/cpu.go
exec/disk.go
exec/mem.go
exec/process.go
exec/process_kill.go
exec/process_stop.go
go.mod
go.sum

chaosblade-io/chaosblade#319
chaosblade-io/chaosblade-spec-go#13
Integrate into the chaosblade tool for testing.

feature: replace ps command to gopsutil

---

Makefile
build/spec.go
exec/bin/file/appendfile/appendfile.go
exec/bin/file/chmodfile/chmodfile.go
exec/file.go
exec/file_append.go
exec/file_chmod.go
exec/model/model.go

file experiment, file content append , file permission modification
`./blade create file append --filepath=~/tmp/mock.log --content="hell world"`
`./blade create file chmod --filepath=~/tmp/mock.log --mark=777`

feature:Add file experiment

---

Makefile
exec/bin/file/addfile/addfile.go
exec/bin/file/chmodfile/chmodfile.go
exec/bin/file/deletefile/deletefile.go
exec/bin/file/movefile/movefile.go
exec/file.go
exec/file_add.go
exec/file_append.go
exec/file_chmod.go
exec/file_delete.go
exec/file_move.go

enhancement the file scenario #44 
`blade create file add --filepath="/tmp/aab" --directory`
`blade create file delete --filepath="/tmp/aa"`
`blade create file move --filepath=/tmp/mock.log --target=/root/`

feature:enhancement the file scenario

---

exec/bin/file/addfile/addfile.go
exec/bin/file/deletefile/deletefile.go
exec/bin/file/movefile/movefile.go
exec/file_add.go
exec/file_move.go

`blade create file add --filepath=/temp/11/11.log --auto-create-dir`

feature:file scenario, add auto-create-dir flag

---

exec/bin/burnmem/burnmem.go
exec/mem.go

Can't stop the memory load experiment when creating without `--mode` flag.

bugfix: fix stopping memory load without mode flag

---

exec/cpu.go
exec/disk.go
exec/disk_burn.go
exec/disk_fill.go
exec/file.go
exec/file_add.go
exec/file_append.go
exec/file_chmod.go
exec/file_delete.go
exec/file_move.go
exec/mem.go
exec/network.go
exec/network_corrupt.go
exec/network_delay.go
exec/network_dns.go
exec/network_drop.go
exec/network_duplicate.go
exec/network_loss.go
exec/network_occupy.go
exec/network_reorder.go
exec/process.go
exec/process_kill.go
exec/process_stop.go
exec/script.go
exec/script_delay.go
exec/script_exit.go
go.mod
go.sum

improvement the action use case
#chaosblade 401
blade create file add -h

feature:improvement the action use case

---

exec/executor_ssh.go
go.mod

#53 
use github.com/howeyc/gopass
`blade create cpu load --cpu-percent 60 --ssh-user=root --ssh-port=22 --ssh-host=192.168.01. --channel ssh`
Enter password not displayed

SSH channel password ciphertext input

---

Makefile

Slim down the chaos_*  executable file
- use upx
- -ldflags "-s -w"

feature: slim down the blade toolkit

---

Makefile
exec/bin/tcnetwork/tcnetwork.go
go.mod
go.sum

1. Update version to 0.7.0
2. Resolve the problem that failed to execute chaos network experiments when the ifconfig command does not exist.

chore: update version to 0.7.0 and check ifconfig command avaliable

---

Makefile

#chaosblade-414
improvment UPX compress
use UPX compression: make upx

feature:improvment upx compress

---

exec/bin/dropnetwork/dropnetwork.go
exec/bin/dropnetwork/dropnetwork_test.go
exec/network_drop.go

add a paramater --url-pattern to support drop package by match a url 
1. execute command  `chaos_dropnetwork --start --debug=true --remote-port 80 --url-pattern publish`
2. execute command  `curl http://www.qq.com/publish`, the result is `Empty reply from server`

add a paramater --url-pattern to support drop package by match a url 

---

exec/executor_ssh.go
exec/file_move.go
exec/model/model.go

https://github.com/chaosblade-io/chaosblade/issues/420
````
blade create k8s node-cpu load --cpu-percent 60 --channel ssh --ssh-host 192.168.1.1 --ssh-user root --ssh-key xx.pem
````

ssh channel add key authorization

---

exec/bin/killprocess/killProcess_test.go
exec/bin/killprocess/killprocess.go
exec/bin/stopprocess/stopprocess.go
exec/process.go
exec/process_kill.go
exec/process_stop.go

In some cases, we want to return success even if the process does not exist.
Add `--ignore-not-found` flag to support the process not found.

feature: add ignore-not-found flag in process experiments

---

exec/bin/dropnetwork/dropnetwork.go
exec/bin/dropnetwork/dropnetwork_test.go
exec/network_drop.go

1. add ip parameter
2. add mutil port support
./blade create network drop --destination-ip 10.1.1.1/24 --timeout 60
./blade create network drop --destination-port 80,81 --timeout 60

add ip and mutil port support

---

Makefile
exec/category/category.go
exec/cpu.go
exec/disk_burn.go
exec/disk_fill.go
exec/file_add.go
exec/file_append.go
exec/file_chmod.go
exec/file_delete.go
exec/file_move.go
exec/kernel_delay.go
exec/kernel_error.go
exec/mem.go
exec/network_corrupt.go
exec/network_delay.go
exec/network_dns.go
exec/network_drop.go
exec/network_duplicate.go
exec/network_loss.go
exec/network_occupy.go
exec/network_reorder.go
exec/process_kill.go
exec/process_stop.go
exec/script_delay.go
exec/script_exit.go
go.mod
go.sum

Release v0.10.0

---

Makefile
exec/bin/burncpu/burncpu.go
go.mod
go.sum

fix cpu percentage in container
use `go.uber.org/automaxprocs/maxprocs`

fix cpu percentage in container & update version to 1.0.0

---

exec/bin/burnio/burnio.go

Signed-off-by: xcaspar <changjun.xcj@alibaba-inc.com>
Handling the situation where the os-release file cannot be found.
Use the default value when os-release file is not found.

bugfix: handle the failure to read the os-release file

---

exec/mem.go

avoid-being-killer is invalid when run `blade create mem load --mode ram --mem-percent 50 --avoid-being-killed`

fix: avoid-being-killed is invalid

---

exec/bin/tcnetwork/tcnetwork.go

When the network delay scenario is executed without adding any parameters, destroy will report an error
yes
Before destroy, judge whether there are parameters during create. If not, TC filter del will not be executed.
no parameter create blade,after success，destroy this blade

Fix the problem of destroy reporting an error when the network does not add any parameters.

---

exec/network/network_dns.go

network dns support multiple domain
Fixes: https://github.com/chaosblade-io/chaosblade-exec-docker/issues/25
multiple domains can be configured, separated by commas (,)
go test ./...

network dns support multiple domain

---

exec/network/tc/network_tc.go

fix: network destroy

---

Makefile

update verison from 1.6.0 to 1.6.1

---

exec/file/file_move.go

Fixes:https://github.com/chaosblade-io/chaosblade/issues/795

move file backup

---

exec/network/tc/network_corrupt.go
exec/network/tc/network_delay.go
exec/network/tc/network_duplicate.go
exec/network/tc/network_loss.go
exec/network/tc/network_reorder.go
exec/network/tc/network_tc.go
exec/network/tc/network_tc_test.go

feature: Add tc protocol filter and test file

---

exec/process/process.go

feature:add multi pid parse(no need if else) 

---

exec/file/file_chmod.go

fix issue: https://github.com/chaosblade-io/chaosblade/issues/884

fix file chmod bug

---

exec/network/tc/network_tc.go
exec/network/tc/network_tc_test.go

Describe what this PR does / why we need it
Fixed network scenario port range calculation error
Does this pull request fix one issue?
Fixes [#983](https://github.com/chaosblade-io/chaosblade/issues/983)

fix: portSetToPortRanges miscalculation

---

exec/cpu/cpu.go

Fix wrongs args info logs for cpu cmd.

Fix wrongs args info logs for cpu cmd.

---

exec/cpu/cpu.go
exec/network/tc/network_tc.go
pkg/automaxprocs/cgroups/cgroup_linux.go
pkg/automaxprocs/cgroups/cgroups_linux.go
pkg/automaxprocs/cgroups/errors_linux.go
pkg/automaxprocs/cgroups/mountpoint_linux.go
pkg/automaxprocs/cgroups/subsys_linux.go
pkg/automaxprocs/cgroups/util.go
pkg/automaxprocs/cgroups/util_test.go
pkg/automaxprocs/maxprocs.go
pkg/automaxprocs/runtime/cpu_quota_linux.go
pkg/automaxprocs/runtime/cpu_quota_unsupported.go
pkg/automaxprocs/runtime/runtime.go

RESOLVE https://github.com/chaosblade-io/chaosblade/issues/1079

fix: get correct CPU quota in container runtime

---

exec/mem/mem.go

PART OF https://github.com/chaosblade-io/chaosblade/issues/1095

fix: DO NOT process `avoid-being-killed` for executor with `NSExecChannel`

---

exec/disk/disk_fill.go

When set to 100 percent, calculating the file size may exceed the available size. Because the accuracy is lost in the calculation process.

fix: calculating the file size

---

.github/workflows/ci.yml
.gitignore
Makefile
VERSION_MANAGEMENT.md
cmd/version/main.go
version/version.go

1. Delete manual update version number. Automatically retrieves version information from Git Tags or Git descriptions.
2. Standardize multi-platform compilation specifications.
```
target/
├── chaosblade-1.7.4-linux_amd64/
│   ├── bin/
│   │   ├── chaos_os          # Binary file containing version information
│   │   └── strace
│   └── yaml/
│       └── chaosblade-os-spec-1.7.4.yaml
├── chaosblade-1.7.4-linux_arm64/
│   ├── bin/
│   │   ├── chaos_os
│   │   └── strace
│   └── yaml/
│       └── chaosblade-os-spec-1.7.4.yaml
└── ...
```

Optimize makefile

---

exec/disk/disk_fill.go
exec/file/file_move.go
exec/network/network_occupy.go
exec/process/process_kill.go
exec/process/process_load.go

related issue: https://github.com/chaosblade-io/chaosblade/issues/1220

Fix: fix the cmd args info for chaosblade-exec-os
